### ISSUE TITLE
stats not found

### ISSUE THREAD

**Issue by muellermarkus** [calvinmccarter/kditransform#1]
I tried to load and use the KDITransformer inplace of the QuantileTransformer. I get the error that `stats` has not been found. It seems like the import of the scipy.stats is not working out. You currently import it as `import scipy.stats as spst` but refer to it as `stats`.

https://github.com/calvinmccarter/kditransform/blob/72641da2de7a2bbbfa1790525245db52fccaf5be/kditransform/kdi_transformer.py#L440

**Comment by calvinmccarter** [comment]
@muellermarkus - thanks for catching this! I've pushed a fix (commit 7c6c85d), so this should work now, assuming you're installing from source. (I will update the pypi package soon as well.)

One caveat is that I support `output_distribution='normal'` for backwards-compatibility, but never experimented with it, and I would recommend using the default `output_distribution='uniform'` for most use-cases.

**Comment by calvinmccarter** [comment]
Fixed as of commit https://github.com/calvinmccarter/kditransform/commit/7c6c85d0a7fa140447c96b5545af91f186237d14, which is now uploaded to v0.2 release on PyPI.
